const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('gitbox', {
  selectFolder: () => ipcRenderer.invoke('gitbox:selectFolder'),
  status: (repoPath) => ipcRenderer.invoke('gitbox:status', repoPath),
  branches: (repoPath) => ipcRenderer.invoke('gitbox:branches', repoPath),
  openExternal: (url) => ipcRenderer.invoke('gitbox:openExternal', url),
  spawnTerminal: (repoPath) => ipcRenderer.invoke('terminal:spawn', repoPath),
  writeTerminal: (id, data) => ipcRenderer.send('terminal:write', id, data),
  resizeTerminal: (id, cols, rows) => ipcRenderer.send('terminal:resize', id, cols, rows),
  killTerminal: (id) => ipcRenderer.send('terminal:kill', id),
  onTerminalData: (callback) => ipcRenderer.on('terminal:data', (_, id, data) => callback(id, data)),
  onTerminalExit: (callback) => ipcRenderer.on('terminal:exit', (_, id) => callback(id)),
  remotes: (repoPath) => ipcRenderer.invoke('gitbox:remotes', repoPath),
  tags: (repoPath) => ipcRenderer.invoke('gitbox:tags', repoPath),
  stashes: (repoPath) => ipcRenderer.invoke('gitbox:stashes', repoPath),
  log: (repoPath, maxCount = 20, refName = '') => ipcRenderer.invoke('gitbox:log', repoPath, maxCount, refName),
  stageAll: (repoPath) => ipcRenderer.invoke('gitbox:stageAll', repoPath),
  unstageAll: (repoPath) => ipcRenderer.invoke('gitbox:unstageAll', repoPath),
  discardAll: (repoPath) => ipcRenderer.invoke('gitbox:discardAll', repoPath),
  commitAll: (repoPath, message) => ipcRenderer.invoke('gitbox:commitAll', repoPath, message),
  checkoutBranch: (repoPath, branchName) => ipcRenderer.invoke('gitbox:checkoutBranch', repoPath, branchName),
  fetch: (repoPath, remoteName = 'origin') => ipcRenderer.invoke('gitbox:fetch', repoPath, remoteName),
  pull: (repoPath, remoteName) => ipcRenderer.invoke('gitbox:pull', repoPath, remoteName),
  push: (repoPath, remoteName) => ipcRenderer.invoke('gitbox:push', repoPath, remoteName),
  diffFile: (repoPath, filePath) => ipcRenderer.invoke('gitbox:diffFile', repoPath, filePath),
  stashChanges: (repoPath, stashId) => ipcRenderer.invoke('gitbox:stashChanges', repoPath, stashId),
  diffStashFile: (repoPath, stashId, filePath) => ipcRenderer.invoke('gitbox:diffStashFile', repoPath, stashId, filePath),
  commitFiles: (repoPath, commitId) => ipcRenderer.invoke('gitbox:commitFiles', repoPath, commitId),
  diffCommitFile: (repoPath, commitId, filePath) => ipcRenderer.invoke('gitbox:diffCommitFile', repoPath, commitId, filePath),
  getConfig: (repoPath) => ipcRenderer.invoke('gitbox:getConfig', repoPath),
  setConfig: (repoPath, name, email) => ipcRenderer.invoke('gitbox:setConfig', repoPath, name, email),
  saveFile: (repoPath, filePath, content) => ipcRenderer.invoke('gitbox:saveFile', repoPath, filePath, content),
  storeGet: (key) => ipcRenderer.sendSync('store:get', key),
  storeSet: (key, value) => ipcRenderer.sendSync('store:set', key, value),
  storeDelete: (key) => ipcRenderer.sendSync('store:delete', key),
  minimize: () => ipcRenderer.send('window:minimize'),
  maximize: () => ipcRenderer.send('window:maximize'),
  close: () => ipcRenderer.send('window:close'),
  setZoom: (factor) => ipcRenderer.send('window:zoom', factor),
});
